## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

title = "Cross Process Design House"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Aubrey Coon"
    title = "Cross Process Design House"
    description = "by Aubrey Coon"
    # authorimage = "/images/author-image.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    logoimage = "/images/logo_cross_process_design_house_light_pink.png"
    copyright = "Aubrey Coon"
    since = 2013
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    # github = "<username>"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # microblog = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    # email = "your-email@example.com"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Specialties"
    weight = 200
    identifier = "specialties"
    url = "/specialties/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
