baseURL = "https://crossprocessdesign.com"
languageCode = "en-us"
title = "Cross Process Design House"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[params]
  custom_css = ["css/custom.css"]
  google_analytics_id=""
  homepage_button_link = '/work'
  homepage_button_text = 'Work'
  homepage_intro = 'Welcome to Cross Process Design House'
  homepage_image = ''
  contact_intro = 'Contact'
  contact_name = 'Aubrey J Coon, Owner & Creative Director'
  contact = 'aubrey@crossprocessdesign.com'
  contact_link = 'mailto:aubrey@crossprocessdesign.com'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Design and Marketing Services"
    meta_og_title = "Cross Process Design House"
    meta_og_type = "website"
    meta_og_url = "https://crossprocessdesign.com"
    meta_og_image = ""
    meta_og_description = "Cross Process Design House specializes in design and marketing services for new and established brands."
    meta_twitter_card = "summary"
    meta_twitter_site = "@aubreyaubrey"
    meta_twitter_creator = "@aubreyaubrey"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
